permalink: /:categories/:title.html
#pygments: true
highlighter: pygments
safe: true

paginate: 8
paginate_path: "page:num"

# presonal config
title: Fillzero's Blog

markdown: kramdown

gems: [jekyll-paginate]